version: "3.9"

services:
  dockertest2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hqxsr-dockertest2
    hostname: hqxsr-dockertest2
    networks:
      vlan932:
        ipv4_address: 172.16.132.3
    restart: always
    privileged: true
    tty: true  # Keeps container running

networks:
  vlan932:
    external: true
